### PR TITLE
#7-Create frontend REACT component for a single energizer-Justinas

### LINKED ISSUE #7: As a host, I want to view an energiser with a description of how to run it
- create frontend REACT component for a single energizer
- serve the data to the frontend from an endpoint

### PR DESCRIPTION
**Pull request by JustinasBrazauskas**
## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

I've benn add on Load component for a single energisser,But I can't make proper funcionality,because I don't have API. 

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #7

## Checklist:

- [ ] ] My code follows the style guidelines of this project

- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Comment by bertilnilsson** [comment]
How is this meant to integrate with the work that @AzinYad started last week on PR #15?

**Comment by RobCso** [comment]
We need to build up on the existing work, I thought we have communicated clearly that we will be using Azin's front-end template and the database that bertil helped us to containerize,

**Comment by JustinasBrazauskas** [comment]
"As a host, I want to view an energiser with a description of how to run it#7
create frontend REACT component for a single energizer
serve the data to the frontend from an endpoint"



This task wasn't clear what exactly to do. it's a component? If, yes what component? Next thing I can't implement without API. 
And of course, I can't integrate, because since I try to create a SingleEnergiser component, the Azin front-end template wasn't merged. So I don't have the whole picture.
My question will be what task I should do?

Thank you for your time!


> How is this meant to integrate with the work that @AzinYad started last week on PR #15?

**Comment by bertilnilsson** [comment]
@JustinasBrazauskas Are you asking me?

The story has two subtasks - one for the frontend and one for the backend. The database schema has been merged into main so there should be no blockers for creating the backend endpoint.

Can you refactor your frontend code to work with the structure that has been merged into main? 

You have to coordinate within the team so that all of your code works together.

**Review by bertilnilsson — CHANGES_REQUESTED** [review]
The current state of this PR can't be merged into main since it breaks the existing code (deleting some code like in App.js and db.js) and adding conflicting code.

**Comment by JustinasBrazauskas** [comment]
@bertilnilsson Yeah I'm asking you! 
 that's one is ok, creating the backend endpoint. Understandable.
But another  subtask about fornt end.  What exactly  to do with the front end, is a bit confusing to me.
Yes I done.

**Comment by JustinasBrazauskas** [comment]
Yeah I resolved conflicting code.

**Comment by bertilnilsson** [comment]
> Yeah I resolved conflicting code.

Did you look at the diff on the FIles changed tab? This PR would break the app if it was merged.

**Comment by JustinasBrazauskas** [comment]
I've been deleted all these files.
Can close this branch and get the newst version from main?

**Comment by bertilnilsson** [comment]
> I've been deleted all these files. Can close this branch and get the newst version from main?

You are deleting the files from the project, not just your changes to them. It means for example that if you merged this branch it would delete the App.js. If it's easier for you, then yes maybe close this PR and start a new one based on a branch from the current version of main.

**Pull request closed without merging**
